# Generated by Django 4.0.5 on 2022-06-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('B', 'Bishkek'), ('O', 'Osh'), ('Batken', 'A'), ('N', 'Naryn'), ('D', 'Djalal-Abad'), ('T', 'Talas'), ('Y', 'Ysuk-kol'), ('Ch', 'Chui')], max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo')),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
